add_newline = false
command_timeout = 10000

format = """
[â•­â”€[$username](brown)$hostname: ](bold purple)$directory $git_branch $git_status $rust $package $python $nodejs $php $cmd_duration $time
[â•°â”€$character](bold purple)"""

[character]
success_symbol = "[ï”](bold green)[ï”](bold yellow)[ï”](bold red)"
error_symbol = "[ï”](bold red)[ï”](bold red)[ï”](bold cyan)"
vicmd_symbol = "[ï“ï“](bold green)"

[aws]
disabled = true

[time]
disabled = false
style = "bold red"

[cmd_duration]
disabled = false
min_time = 200

[directory]
truncation_length = 20
truncate_to_repo = false
format = "[$path]($style) [$read_only]($read_only_style) "
style = "fg:blue bold"
read_only_style = "197"
read_only = " ï€£ "
repo_root_style = "fg:cyan bold"
repo_root_format = "ï‡’ repo: [$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[hostname]
disabled = false
ssh_only = false
format = "@[$hostname](bold yellow)"

[nodejs]
symbol = "îœ˜ "

[python]
symbol = "îˆµ "

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
disabled = false

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) â–º "
symbol = "î‚  "
style = "bold purple"
truncation_length = 20

[git_status]
conflicted = "ğŸš©"
ahead = "ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = '$count ï '
stashed = "ğŸ“¦"
modified = "$count ğŸ“"
staged = '[+$count](green) '
renamed = "ğŸ‘…"
deleted = "ğŸ’¥"

[shell]
fish_indicator = "ğŸ¦ˆ"
bash_indicator = "ğŸŒ"
powershell_indicator = "ğŸ’»"
disabled = false

[username]
disabled = false
show_always =true
style_root = "yellow bold"
style_user = "green bold"
format = "[$user]($style)"
